//! Lockfile parsing for Rust ecosystem
//!
//! Supports finding package versions from Cargo.lock

use serde::Deserialize;
use std::fs;
use std::path::{Path, PathBuf};
use thiserror::Error;

#[derive(Error, Debug)]
pub enum LockfileError {
    #[error("No Cargo.lock found. Specify version explicitly.")]
    NotFound,

    #[error(
        "Version not found for '{package}'. Specify explicitly: dotdeps add rust:{package}@<version>"
    )]
    VersionNotFound { package: String },

    #[error("Failed to read {path}: {source}")]
    ReadFile {
        path: PathBuf,
        source: std::io::Error,
    },

    #[error("Failed to parse {path}: {details}")]
    Parse { path: PathBuf, details: String },
}

/// Find the version of a crate by searching Cargo.lock
///
/// Searches upward from the current directory for Cargo.lock
pub fn find_version(package: &str) -> Result<String, LockfileError> {
    let lockfile = find_lockfile()?;
    parse_version_from_lockfile(&lockfile, package)
}

/// Find the nearest Cargo.lock by walking up from current directory
fn find_lockfile() -> Result<PathBuf, LockfileError> {
    let cwd = std::env::current_dir().map_err(|_| LockfileError::NotFound)?;

    let mut dir = cwd.as_path();
    loop {
        let path = dir.join("Cargo.lock");
        if path.exists() {
            return Ok(path);
        }

        // Move to parent directory
        match dir.parent() {
            Some(parent) => dir = parent,
            None => break,
        }
    }

    Err(LockfileError::NotFound)
}

/// Structure for Cargo.lock files
///
/// Cargo.lock is TOML with a `[[package]]` array containing name and version
#[derive(Deserialize)]
struct CargoLockfile {
    package: Option<Vec<CargoPackage>>,
}

#[derive(Deserialize)]
struct CargoPackage {
    name: String,
    version: String,
}

/// Parse version from Cargo.lock
fn parse_version_from_lockfile(path: &Path, package: &str) -> Result<String, LockfileError> {
    let content = fs::read_to_string(path).map_err(|source| LockfileError::ReadFile {
        path: path.to_path_buf(),
        source,
    })?;

    let lockfile: CargoLockfile = toml::from_str(&content).map_err(|e| LockfileError::Parse {
        path: path.to_path_buf(),
        details: e.to_string(),
    })?;

    let packages = lockfile.package.unwrap_or_default();
    let normalized_package = normalize_crate_name(package);

    // Crate names are case-insensitive and use - or _ interchangeably
    for pkg in packages {
        if normalize_crate_name(&pkg.name) == normalized_package {
            return Ok(pkg.version);
        }
    }

    Err(LockfileError::VersionNotFound {
        package: package.to_string(),
    })
}

/// Normalize crate name for comparison
///
/// Crate names are case-insensitive and treat - and _ as equivalent
fn normalize_crate_name(name: &str) -> String {
    name.to_lowercase().replace('-', "_")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_normalize_crate_name() {
        assert_eq!(normalize_crate_name("Serde"), "serde");
        assert_eq!(normalize_crate_name("serde-json"), "serde_json");
        assert_eq!(normalize_crate_name("serde_json"), "serde_json");
        assert_eq!(normalize_crate_name("SERDE-JSON"), "serde_json");
    }

    #[test]
    fn test_parse_cargo_lockfile_content() {
        let content = r#"
# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "serde"
version = "1.0.228"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "abc123"

[[package]]
name = "serde_json"
version = "1.0.149"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "def456"
dependencies = [
  "serde",
]
"#;

        let lockfile: CargoLockfile = toml::from_str(content).unwrap();
        let packages = lockfile.package.unwrap();

        assert_eq!(packages.len(), 2);
        assert_eq!(packages[0].name, "serde");
        assert_eq!(packages[0].version, "1.0.228");
        assert_eq!(packages[1].name, "serde_json");
        assert_eq!(packages[1].version, "1.0.149");
    }

    #[test]
    fn test_parse_cargo_lockfile_with_hyphen_underscore() {
        let content = r#"
[[package]]
name = "serde-json"
version = "1.0.149"
"#;

        let lockfile: CargoLockfile = toml::from_str(content).unwrap();
        let packages = lockfile.package.unwrap();

        assert_eq!(packages[0].name, "serde-json");

        // Test normalization finds both variants
        assert_eq!(normalize_crate_name("serde-json"), "serde_json");
        assert_eq!(normalize_crate_name("serde_json"), "serde_json");
    }
}
